name:                 FormValidation
highlighter:          pygments

source:               .
destination:          ../output
keep_files:           ["bundles"]
markdown:             kramdown
exclude:              ['node_modules', '*.less', '*.programmatic', '*.declarative', '*.markup', '*.md', '.gitignore', 'Gemfile']
url:                  http://formvalidation.io

paginate:             5
paginate_path:        /news/page:num
encoding:             UTF-8
relative_permalinks:  false
permalink:            /news/:title/
timezone:             Asia/Ho_Chi_Minh

# Custom variables
# not defined by Jekyll
description:          FormValidation - The best jQuery validation plugin to validate form fields, support Bootstrap, Zurb Foundation, Pure, Semantic, UIKit frameworks
license:
  developer:
    price:            50$
    gumroad_url:      https://gum.co/formvalidation-developer-license
    sellfy_url:       https://sellfy.com/p/uitF/
    sellfy_id:        uitF
  organization:
    price:            200$
    gumroad_url:      https://gum.co/formvalidation-organization-license
    sellfy_url:       https://sellfy.com/p/eQiZ/
    sellfy_id:        eQiZ
current_version:      0.8.1
change_log:           /news/v0-8-1-released-supports-bootstrap-4-alpha-3/
released_date:        2016.07.29
support:              https://github.com/formvalidation/support/issues
ga_code:              UA-44786951-2

# Plugins
asset_bundler:
  dev: false
  base_path: /bundles/
  markup_templates:
    js: <script src="{{url}}"></script>
    css: <link href="{{url}}" rel="stylesheet">